"""Increased insight text capacity

Revision ID: 44af9d2b1504
Revises: 16314a5f97be
Create Date: 2024-02-16 18:57:54.710170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44af9d2b1504'
down_revision = '16314a5f97be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=5000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
